### ISSUE TITLE
Week 4 (Oct 25-Oct 31)

### ISSUE THREAD

**Issue by jonykarki** [jonykarki/ML-Reproducibility-Challenge-2020#15]
- [x] Attempt to train models with batch size 16 and 32
- [ ] Work on draft
- [ ] Comment on code
- [x] start making table

**Comment by asimsedhain** [comment]
Default path for training data path in https://github.com/jonykarki/ML-Reproducibility-Challenge-2020/blob/main/train_color_denoising.py is set to BSD400 image dataset.
https://github.com/jonykarki/ML-Reproducibility-Challenge-2020/blob/1a1c5b4423db7498f0e0800f84de4c4bedfb01c9/train_color_denoising.py#L58

**Comment by asimsedhain** [comment]
Future note:

If we get the same psnr by training on batch size 2, then why are the authors training on batch size 32?
